/**
 * Smart Search Training Data
 * Contains condition profiles and matching logic for AI-powered practitioner recommendations
 */

export interface ConditionProfile {
  id: string;
  name: string;
  keywords: string[];
  symptoms: string[];
  relatedConditions: string[];
  recommendedPractitioners: ('sports_therapist' | 'osteopath' | 'massage_therapist')[];
  recommendedServices: string[];
  treatmentApproaches: string[];
  urgencyLevel: 'low' | 'medium' | 'high';
  typicalDuration: string;
  expectedOutcomes: string[];
  bodyParts: string[];
  severity: 'mild' | 'moderate' | 'severe';
}

export const conditionsDatabase: ConditionProfile[] = [
  {
    id: 'lower_back_pain',
    name: 'Lower Back Pain',
    keywords: ['lower back pain', 'lumbar pain', 'back ache', 'spine pain', 'sciatica', 'disc pain', 'herniated disc', 'slipped disc', 'can\'t stand up straight', 'back spasm', 'lower back hurts', 'my back is killing me', 'back problem', 'can\'t stand', 'back pain started', 'hurt my back', 'back injury', 'my back'],
    symptoms: ['pain when sitting', 'stiffness in lower back', 'difficulty bending', 'shooting pain down leg', 'muscle spasms in back', 'can\'t stand up straight', 'wake up with back pain', 'pain getting worse', 'can\'t sit down', 'pain when standing'],
    relatedConditions: ['sciatica', 'disc_issues', 'muscle_strain', 'spinal_stenosis'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['initial_consultation', 'treatment', 'rehabilitation'],
    treatmentApproaches: ['manual therapy', 'exercise rehabilitation', 'postural advice', 'spinal manipulation'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['reduced pain', 'improved mobility', 'better posture'],
    bodyParts: ['lower_back', 'spine', 'pelvis'],
    severity: 'moderate'
  },
  {
    id: 'sports_injury',
    name: 'Sports Injury',
    keywords: ['sports injury', 'athletic injury', 'hurt myself playing', 'training injury', 'pulled muscle', 'muscle strain', 'acute injury', 'hurt at the gym', 'hurt working out', 'hurt playing', 'tweaked something', 'felt a pop', 'heard a crack', 'strained it', 'tore something', 'hurt it in training'],
    symptoms: ['swelling after activity', 'bruising', 'sharp pain', 'limited movement', 'instability', 'can\'t play', 'can\'t run', 'sudden pain', 'can\'t use it', 'felt something go', 'heard a snap'],
    relatedConditions: ['muscle_tear', 'ligament_damage', 'tendonitis', 'overuse'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'rehabilitation', 'performance_training'],
    treatmentApproaches: ['injury assessment', 'rehabilitation program', 'return to sport', 'prevention'],
    urgencyLevel: 'high',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['full recovery', 'safe return to activity', 'injury prevention'],
    bodyParts: ['knee', 'ankle', 'shoulder', 'elbow', 'hip'],
    severity: 'moderate'
  },
  {
    id: 'stress_tension',
    name: 'Stress & Tension',
    keywords: ['stress relief', 'tension headache', 'tight muscles', 'muscle tension', 'work stress', 'burnout', 'overwhelmed', 'need to relax', 'de-stress', 'unwind', 'mental fatigue', 'exhausted', 'anxiety', 'worry', 'pressure', 'can\'t switch off', 'feeling stressed', 'tense all over', 'shoulder tension', 'back tension', 'just want to relax', 'need a massage', 'want to relax'],
    symptoms: ['tight shoulders', 'neck pain from tension', 'tension headaches', 'poor sleep', 'fatigue', 'can\'t relax', 'always tense', 'jaws clenched', 'shoulders up to ears', 'can\'t sleep because stressed', 'racing mind', 'always worried'],
    relatedConditions: ['tension_headaches', 'muscle_tension', 'anxiety', 'burnout'],
    recommendedPractitioners: ['massage_therapist', 'osteopath'],
    recommendedServices: ['massage', 'maintenance', 'wellness'],
    treatmentApproaches: ['relaxation massage', 'myofascial release', 'stress management', 'breathing techniques'],
    urgencyLevel: 'low',
    typicalDuration: '1-4 sessions',
    expectedOutcomes: ['reduced tension', 'better sleep', 'improved wellbeing'],
    bodyParts: ['neck', 'shoulders', 'upper_back', 'head'],
    severity: 'mild'
  },
  {
    id: 'neck_pain',
    name: 'Neck Pain',
    keywords: ['neck', 'cervical', 'whiplash', 'stiff neck', 'crick', 'neck hurts', 'neck pain', 'can\'t turn my head', 'sore neck', 'neck problem', 'my neck'],
    symptoms: ['neck stiffness', 'headaches', 'limited rotation', 'muscle tension', 'can\'t look over shoulder', 'pain turning head', 'neck feels locked'],
    relatedConditions: ['whiplash', 'cervical_strain', 'tension_headaches'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['initial_consultation', 'treatment', 'maintenance'],
    treatmentApproaches: ['cervical manipulation', 'soft tissue work', 'postural correction'],
    urgencyLevel: 'medium',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['improved range of motion', 'reduced pain', 'better posture'],
    bodyParts: ['neck', 'cervical_spine', 'shoulders'],
    severity: 'moderate'
  },
  {
    id: 'knee_problems',
    name: 'Knee Problems',
    keywords: ['knee', 'patella', 'meniscus', 'arthritis', 'runner\'s knee'],
    symptoms: ['knee pain', 'swelling', 'clicking', 'instability', 'difficulty walking'],
    relatedConditions: ['patellofemoral_pain', 'meniscal_tear', 'osteoarthritis'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'rehabilitation', 'treatment'],
    treatmentApproaches: ['strengthening exercises', 'manual therapy', 'movement correction'],
    urgencyLevel: 'medium',
    typicalDuration: '6-10 sessions',
    expectedOutcomes: ['reduced pain', 'improved function', 'better movement patterns'],
    bodyParts: ['knee', 'patella', 'thigh', 'calf'],
    severity: 'moderate'
  },
  {
    id: 'shoulder_issues',
    name: 'Shoulder Issues',
    keywords: ['shoulder', 'rotator cuff', 'frozen shoulder', 'impingement'],
    symptoms: ['shoulder pain', 'limited movement', 'weakness', 'night pain'],
    relatedConditions: ['rotator_cuff_tear', 'frozen_shoulder', 'impingement_syndrome'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'rehabilitation', 'treatment'],
    treatmentApproaches: ['strengthening', 'mobility work', 'manual therapy'],
    urgencyLevel: 'medium',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['improved range of motion', 'reduced pain', 'better function'],
    bodyParts: ['shoulder', 'upper_arm', 'scapula'],
    severity: 'moderate'
  },
  {
    id: 'post_surgery_recovery',
    name: 'Post-Surgery Recovery',
    keywords: ['surgery', 'post-operative', 'recovery', 'rehabilitation', 'scar tissue'],
    symptoms: ['scar tissue', 'limited movement', 'weakness', 'swelling'],
    relatedConditions: ['surgical_recovery', 'scar_adhesions', 'muscle_atrophy'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['rehabilitation', 'treatment', 'follow_up'],
    treatmentApproaches: ['graduated exercise', 'scar tissue work', 'functional training'],
    urgencyLevel: 'high',
    typicalDuration: '8-16 sessions',
    expectedOutcomes: ['restored function', 'reduced scar tissue', 'full recovery'],
    bodyParts: ['various'],
    severity: 'moderate'
  },
  {
    id: 'chronic_pain',
    name: 'Chronic Pain',
    keywords: ['chronic', 'ongoing', 'persistent', 'long-term', 'fibromyalgia'],
    symptoms: ['persistent pain', 'fatigue', 'sleep issues', 'mood changes'],
    relatedConditions: ['fibromyalgia', 'chronic_fatigue', 'central_sensitization'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['treatment', 'maintenance', 'wellness'],
    treatmentApproaches: ['gentle therapy', 'pain management', 'lifestyle advice'],
    urgencyLevel: 'medium',
    typicalDuration: 'ongoing',
    expectedOutcomes: ['pain management', 'improved quality of life', 'better coping'],
    bodyParts: ['various'],
    severity: 'severe'
  },
  {
    id: 'postural_issues',
    name: 'Postural Issues',
    keywords: ['poor posture', 'posture correction', 'desk work posture', 'forward head posture', 'rounded shoulders'],
    symptoms: ['poor posture', 'muscle fatigue from sitting', 'back pain from posture', 'neck tension'],
    relatedConditions: ['forward_head_posture', 'kyphosis', 'muscle_imbalance'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['initial_consultation', 'treatment', 'follow_up'],
    treatmentApproaches: ['postural correction', 'strengthening', 'education'],
    urgencyLevel: 'low',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['improved posture', 'reduced pain', 'better habits'],
    bodyParts: ['spine', 'shoulders', 'neck'],
    severity: 'mild'
  },
  {
    id: 'pregnancy_related',
    name: 'Pregnancy-Related Issues',
    keywords: ['pregnancy', 'prenatal', 'postnatal', 'maternity', 'baby'],
    symptoms: ['back pain', 'pelvic pain', 'sciatica', 'round ligament pain'],
    relatedConditions: ['pregnancy_back_pain', 'pelvic_girdle_pain', 'diastasis'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['prenatal_care', 'treatment', 'wellness'],
    treatmentApproaches: ['gentle therapy', 'support techniques', 'education'],
    urgencyLevel: 'medium',
    typicalDuration: 'ongoing',
    expectedOutcomes: ['reduced discomfort', 'better mobility', 'preparation for birth'],
    bodyParts: ['pelvis', 'lower_back', 'abdomen'],
    severity: 'moderate'
  },
  {
    id: 'headaches_migraines',
    name: 'Headaches & Migraines',
    keywords: ['headache', 'migraine', 'head pain', 'tension headache', 'cluster headache'],
    symptoms: ['head pain', 'throbbing', 'sensitivity to light', 'nausea', 'neck tension'],
    relatedConditions: ['tension_headaches', 'migraine', 'cervicogenic_headache'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['treatment', 'maintenance', 'wellness'],
    treatmentApproaches: ['cervical treatment', 'stress management', 'trigger identification'],
    urgencyLevel: 'medium',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['reduced frequency', 'less severe episodes', 'better management'],
    bodyParts: ['head', 'neck', 'shoulders'],
    severity: 'moderate'
  },
  {
    id: 'hip_pain',
    name: 'Hip Pain',
    keywords: ['hip', 'hip pain', 'groin pain', 'hip joint', 'can\'t walk properly'],
    symptoms: ['hip pain', 'groin pain', 'difficulty walking', 'limited movement', 'clicking'],
    relatedConditions: ['hip_impingement', 'labral_tear', 'osteoarthritis'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['initial_consultation', 'treatment', 'rehabilitation'],
    treatmentApproaches: ['mobility work', 'strengthening', 'movement correction'],
    urgencyLevel: 'medium',
    typicalDuration: '6-10 sessions',
    expectedOutcomes: ['improved mobility', 'reduced pain', 'better function'],
    bodyParts: ['hip', 'pelvis', 'thigh'],
    severity: 'moderate'
  },
  {
    id: 'ankle_foot_issues',
    name: 'Ankle & Foot Issues',
    keywords: ['ankle', 'foot', 'foot pain', 'ankle pain', 'plantar fasciitis', 'heel pain'],
    symptoms: ['foot pain', 'ankle pain', 'heel pain', 'difficulty walking', 'morning stiffness'],
    relatedConditions: ['plantar_fasciitis', 'ankle_sprain', 'achilles_tendonitis'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'treatment', 'rehabilitation'],
    treatmentApproaches: ['soft tissue work', 'strengthening', 'gait analysis'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['reduced pain', 'improved walking', 'better function'],
    bodyParts: ['ankle', 'foot', 'heel', 'calf'],
    severity: 'moderate'
  },
  {
    id: 'elbow_wrist_issues',
    name: 'Elbow & Wrist Issues',
    keywords: ['elbow', 'wrist', 'tennis elbow', 'golfer\'s elbow', 'carpal tunnel', 'RSI'],
    symptoms: ['elbow pain', 'wrist pain', 'numbness', 'weakness', 'difficulty gripping'],
    relatedConditions: ['tennis_elbow', 'golfers_elbow', 'carpal_tunnel', 'RSI'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'treatment', 'rehabilitation'],
    treatmentApproaches: ['soft tissue work', 'strengthening', 'ergonomic advice'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['reduced pain', 'improved function', 'better ergonomics'],
    bodyParts: ['elbow', 'wrist', 'forearm', 'hand'],
    severity: 'moderate'
  },
  {
    id: 'tmj_jaw_issues',
    name: 'TMJ & Jaw Issues',
    keywords: ['jaw', 'TMJ', 'jaw pain', 'clicking jaw', 'lockjaw', 'teeth grinding'],
    symptoms: ['jaw pain', 'clicking', 'locking', 'difficulty chewing', 'headaches'],
    relatedConditions: ['TMJ_dysfunction', 'bruxism', 'jaw_misalignment'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['initial_consultation', 'treatment', 'maintenance'],
    treatmentApproaches: ['jaw mobilization', 'muscle work', 'stress management'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['reduced pain', 'improved function', 'better sleep'],
    bodyParts: ['jaw', 'face', 'neck'],
    severity: 'moderate'
  },
  {
    id: 'repetitive_strain',
    name: 'Repetitive Strain Injury',
    keywords: ['RSI', 'repetitive strain', 'overuse', 'computer work', 'typing', 'mouse arm'],
    symptoms: ['muscle fatigue', 'pain with movement', 'weakness', 'numbness', 'burning'],
    relatedConditions: ['tendonitis', 'carpal_tunnel', 'muscle_strain'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'treatment', 'rehabilitation'],
    treatmentApproaches: ['ergonomic assessment', 'strengthening', 'workplace modifications'],
    urgencyLevel: 'medium',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['reduced pain', 'improved ergonomics', 'prevention'],
    bodyParts: ['arms', 'hands', 'shoulders', 'neck'],
    severity: 'moderate'
  },
  {
    id: 'sleep_issues',
    name: 'Sleep-Related Issues',
    keywords: ['sleep', 'insomnia', 'can\'t sleep', 'sleep problems', 'restless', 'tired'],
    symptoms: ['difficulty sleeping', 'restlessness', 'muscle tension', 'fatigue', 'stress'],
    relatedConditions: ['insomnia', 'stress', 'muscle_tension'],
    recommendedPractitioners: ['massage_therapist', 'osteopath'],
    recommendedServices: ['wellness', 'maintenance', 'treatment'],
    treatmentApproaches: ['relaxation techniques', 'stress management', 'gentle therapy'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['better sleep', 'reduced tension', 'improved wellbeing'],
    bodyParts: ['whole_body', 'mind'],
    severity: 'mild'
  },
  {
    id: 'workplace_injuries',
    name: 'Workplace Injuries',
    keywords: ['work injury', 'workplace', 'lifting injury', 'slip and fall', 'work accident'],
    symptoms: ['sudden pain', 'limited movement', 'swelling', 'bruising', 'difficulty working'],
    relatedConditions: ['acute_injury', 'muscle_strain', 'ligament_damage'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['initial_consultation', 'treatment', 'rehabilitation'],
    treatmentApproaches: ['injury assessment', 'pain management', 'return to work'],
    urgencyLevel: 'high',
    typicalDuration: '4-12 sessions',
    expectedOutcomes: ['pain relief', 'restored function', 'safe return to work'],
    bodyParts: ['various'],
    severity: 'moderate'
  },
  {
    id: 'age_related_issues',
    name: 'Age-Related Issues',
    keywords: ['aging', 'elderly', 'senior', 'age-related', 'wear and tear', 'arthritis'],
    symptoms: ['joint stiffness', 'reduced mobility', 'morning stiffness', 'general aches'],
    relatedConditions: ['osteoarthritis', 'general_wear', 'muscle_loss'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['maintenance', 'wellness', 'treatment'],
    treatmentApproaches: ['gentle therapy', 'mobility work', 'lifestyle advice'],
    urgencyLevel: 'low',
    typicalDuration: 'ongoing',
    expectedOutcomes: ['maintained mobility', 'pain management', 'better quality of life'],
    bodyParts: ['various'],
    severity: 'mild'
  },
  {
    id: 'desk_worker_syndrome',
    name: 'Desk Worker Syndrome',
    keywords: ['desk job', 'office work', 'computer work', 'sitting all day', 'office chair', 'work from home', 'wfh', 'remote work'],
    symptoms: ['back pain from sitting', 'neck pain', 'shoulder tension', 'hip tightness', 'poor posture', 'can\'t sit properly'],
    relatedConditions: ['forward_head_posture', 'hip_flexor_tightness', 'upper_cross_syndrome'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['postural_assessment', 'ergonomic_consultation', 'treatment'],
    treatmentApproaches: ['postural correction', 'ergonomic advice', 'strengthening', 'stretching'],
    urgencyLevel: 'low',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['better posture', 'reduced pain', 'improved ergonomics'],
    bodyParts: ['spine', 'neck', 'shoulders', 'hips'],
    severity: 'mild'
  },
  {
    id: 'gym_injuries',
    name: 'Gym & Fitness Injuries',
    keywords: ['gym injury', 'workout injury', 'lifting injury', 'gym pain', 'fitness injury', 'weight training', 'crossfit'],
    symptoms: ['muscle strain', 'joint pain', 'overuse injury', 'can\'t lift properly', 'form issues'],
    relatedConditions: ['muscle_strain', 'tendonitis', 'overuse_injury'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['injury_assessment', 'movement_analysis', 'rehabilitation'],
    treatmentApproaches: ['injury assessment', 'movement correction', 'strengthening', 'prevention'],
    urgencyLevel: 'medium',
    typicalDuration: '4-10 sessions',
    expectedOutcomes: ['pain relief', 'better form', 'injury prevention'],
    bodyParts: ['shoulders', 'back', 'knees', 'elbows'],
    severity: 'moderate'
  },
  {
    id: 'running_injuries',
    name: 'Running Injuries',
    keywords: ['running injury', 'runner\'s knee', 'shin splints', 'running pain', 'marathon training', 'jogging'],
    symptoms: ['knee pain', 'shin pain', 'foot pain', 'hip pain', 'can\'t run properly'],
    relatedConditions: ['patellofemoral_pain', 'shin_splints', 'plantar_fasciitis'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['gait_analysis', 'injury_assessment', 'rehabilitation'],
    treatmentApproaches: ['gait analysis', 'strengthening', 'biomechanical correction'],
    urgencyLevel: 'medium',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['pain-free running', 'better form', 'injury prevention'],
    bodyParts: ['knees', 'shins', 'feet', 'hips'],
    severity: 'moderate'
  },
  {
    id: 'cycling_injuries',
    name: 'Cycling Injuries',
    keywords: ['cycling injury', 'bike pain', 'cycling pain', 'bike fit', 'saddle pain', 'cycling discomfort'],
    symptoms: ['back pain', 'neck pain', 'knee pain', 'saddle discomfort', 'numbness'],
    relatedConditions: ['bike_fit_issues', 'overuse_injury', 'postural_strain'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['bike_fit_assessment', 'injury_treatment', 'postural_correction'],
    treatmentApproaches: ['bike fit assessment', 'postural correction', 'strengthening'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['comfortable cycling', 'better bike fit', 'reduced pain'],
    bodyParts: ['back', 'neck', 'knees', 'pelvis'],
    severity: 'mild'
  },
  {
    id: 'yoga_injuries',
    name: 'Yoga Injuries',
    keywords: ['yoga injury', 'yoga pain', 'overstretching', 'yoga strain', 'flexibility injury'],
    symptoms: ['muscle strain', 'joint pain', 'overstretching', 'can\'t do poses'],
    relatedConditions: ['muscle_strain', 'joint_hyperextension', 'overuse_injury'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['movement_assessment', 'injury_treatment', 'flexibility_guidance'],
    treatmentApproaches: ['movement assessment', 'injury treatment', 'flexibility guidance'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['safe practice', 'injury healing', 'better flexibility'],
    bodyParts: ['spine', 'hips', 'shoulders', 'knees'],
    severity: 'mild'
  },
  {
    id: 'parent_back_pain',
    name: 'Parent Back Pain',
    keywords: ['parent back pain', 'lifting kids', 'carrying baby', 'parenting pain', 'baby carrying'],
    symptoms: ['back pain from lifting', 'shoulder pain', 'neck strain', 'can\'t pick up kids'],
    relatedConditions: ['lifting_injury', 'postural_strain', 'muscle_imbalance'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['lifting_technique', 'postural_correction', 'treatment'],
    treatmentApproaches: ['lifting technique education', 'postural correction', 'strengthening'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['pain-free parenting', 'better lifting technique', 'strength improvement'],
    bodyParts: ['back', 'shoulders', 'neck'],
    severity: 'moderate'
  },
  {
    id: 'student_neck_pain',
    name: 'Student Neck Pain',
    keywords: ['student pain', 'studying pain', 'text neck', 'phone neck', 'laptop posture'],
    symptoms: ['neck pain from studying', 'text neck', 'shoulder tension', 'headaches'],
    relatedConditions: ['text_neck', 'forward_head_posture', 'muscle_tension'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['postural_assessment', 'ergonomic_advice', 'treatment'],
    treatmentApproaches: ['postural correction', 'ergonomic advice', 'strengthening'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['better posture', 'reduced pain', 'study comfort'],
    bodyParts: ['neck', 'shoulders', 'upper_back'],
    severity: 'mild'
  },
  {
    id: 'driving_pain',
    name: 'Driving Pain',
    keywords: ['driving pain', 'car pain', 'commute pain', 'long drive', 'driving discomfort'],
    symptoms: ['back pain from driving', 'neck pain', 'hip stiffness', 'leg pain'],
    relatedConditions: ['postural_strain', 'muscle_tension', 'circulation_issues'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['postural_assessment', 'ergonomic_advice', 'treatment'],
    treatmentApproaches: ['postural correction', 'ergonomic advice', 'stretching'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['comfortable driving', 'reduced pain', 'better posture'],
    bodyParts: ['back', 'neck', 'hips', 'legs'],
    severity: 'mild'
  },
  {
    id: 'gardening_injuries',
    name: 'Gardening Injuries',
    keywords: ['gardening pain', 'gardening injury', 'yard work', 'landscaping pain', 'digging pain'],
    symptoms: ['back pain from gardening', 'knee pain', 'shoulder strain', 'can\'t garden'],
    relatedConditions: ['lifting_injury', 'overuse_injury', 'postural_strain'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['movement_assessment', 'injury_treatment', 'prevention'],
    treatmentApproaches: ['movement education', 'injury treatment', 'prevention strategies'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['pain-free gardening', 'better technique', 'injury prevention'],
    bodyParts: ['back', 'knees', 'shoulders'],
    severity: 'mild'
  },
  {
    id: 'sleep_position_pain',
    name: 'Sleep Position Pain',
    keywords: ['sleep pain', 'sleeping position', 'wake up pain', 'bed pain', 'pillow pain'],
    symptoms: ['morning pain', 'sleeping discomfort', 'wake up stiff', 'can\'t sleep comfortably'],
    relatedConditions: ['sleep_position_issues', 'pillow_problems', 'mattress_issues'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['sleep_assessment', 'postural_advice', 'treatment'],
    treatmentApproaches: ['sleep position advice', 'pillow recommendations', 'treatment'],
    urgencyLevel: 'low',
    typicalDuration: '2-4 sessions',
    expectedOutcomes: ['better sleep', 'reduced morning pain', 'comfortable sleep'],
    bodyParts: ['neck', 'back', 'shoulders'],
    severity: 'mild'
  },
  {
    id: 'pregnancy_back_pain',
    name: 'Pregnancy Back Pain',
    keywords: ['pregnant back pain', 'pregnancy pain', 'baby bump pain', 'maternity pain'],
    symptoms: ['back pain during pregnancy', 'pelvic pain', 'sciatica', 'round ligament pain'],
    relatedConditions: ['pregnancy_back_pain', 'pelvic_girdle_pain', 'sciatica'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['prenatal_care', 'gentle_treatment', 'support'],
    treatmentApproaches: ['gentle therapy', 'support techniques', 'education'],
    urgencyLevel: 'medium',
    typicalDuration: 'ongoing',
    expectedOutcomes: ['reduced discomfort', 'better mobility', 'birth preparation'],
    bodyParts: ['back', 'pelvis', 'hips'],
    severity: 'moderate'
  },
  {
    id: 'postpartum_recovery',
    name: 'Postpartum Recovery',
    keywords: ['postpartum pain', 'after birth', 'new mom pain', 'postnatal recovery'],
    symptoms: ['back pain after birth', 'pelvic pain', 'muscle weakness', 'posture issues'],
    relatedConditions: ['postpartum_recovery', 'diastasis', 'pelvic_floor_issues'],
    recommendedPractitioners: ['osteopath', 'sports_therapist'],
    recommendedServices: ['postpartum_rehabilitation', 'core_strengthening', 'treatment'],
    treatmentApproaches: ['graduated exercise', 'core strengthening', 'postural correction'],
    urgencyLevel: 'medium',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['strength recovery', 'pain relief', 'better function'],
    bodyParts: ['core', 'pelvis', 'back'],
    severity: 'moderate'
  },
  {
    id: 'menopause_joint_pain',
    name: 'Menopause Joint Pain',
    keywords: ['menopause pain', 'menopausal pain', 'hormonal pain', 'joint pain menopause'],
    symptoms: ['joint stiffness', 'muscle aches', 'bone pain', 'general discomfort'],
    relatedConditions: ['hormonal_changes', 'bone_density_issues', 'muscle_loss'],
    recommendedPractitioners: ['osteopath', 'massage_therapist'],
    recommendedServices: ['gentle_treatment', 'mobility_work', 'wellness'],
    treatmentApproaches: ['gentle therapy', 'mobility work', 'lifestyle advice'],
    urgencyLevel: 'low',
    typicalDuration: 'ongoing',
    expectedOutcomes: ['pain management', 'maintained mobility', 'better quality of life'],
    bodyParts: ['joints', 'muscles', 'bones'],
    severity: 'mild'
  },
  {
    id: 'weekend_warrior_injuries',
    name: 'Weekend Warrior Injuries',
    keywords: ['weekend warrior', 'weekend athlete', 'recreational injury', 'weekend sports'],
    symptoms: ['acute injury', 'muscle strain', 'joint pain', 'overexertion'],
    relatedConditions: ['acute_injury', 'muscle_strain', 'overuse_injury'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['injury_assessment', 'rehabilitation', 'prevention'],
    treatmentApproaches: ['injury assessment', 'rehabilitation', 'prevention education'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['injury recovery', 'prevention strategies', 'better preparation'],
    bodyParts: ['various'],
    severity: 'moderate'
  },
  {
    id: 'hiking_injuries',
    name: 'Hiking Injuries',
    keywords: ['hiking injury', 'trail pain', 'hiking pain', 'backpack pain', 'trekking injury'],
    symptoms: ['knee pain from hiking', 'back pain', 'foot pain', 'shoulder strain'],
    relatedConditions: ['overuse_injury', 'equipment_issues', 'terrain_adaptation'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['equipment_assessment', 'injury_treatment', 'prevention'],
    treatmentApproaches: ['equipment assessment', 'injury treatment', 'prevention strategies'],
    urgencyLevel: 'low',
    typicalDuration: '3-6 sessions',
    expectedOutcomes: ['pain-free hiking', 'better equipment', 'injury prevention'],
    bodyParts: ['knees', 'back', 'feet', 'shoulders'],
    severity: 'mild'
  },
  {
    id: 'dance_injuries',
    name: 'Dance Injuries',
    keywords: ['dance injury', 'dancing pain', 'dance strain', 'performance injury'],
    symptoms: ['dance-related pain', 'overuse injury', 'technique issues', 'performance pain'],
    relatedConditions: ['overuse_injury', 'technique_issues', 'performance_strain'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['movement_analysis', 'injury_treatment', 'technique_correction'],
    treatmentApproaches: ['movement analysis', 'injury treatment', 'technique correction'],
    urgencyLevel: 'medium',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['pain-free dancing', 'better technique', 'injury prevention'],
    bodyParts: ['feet', 'ankles', 'knees', 'hips', 'back'],
    severity: 'moderate'
  },
  {
    id: 'martial_arts_injuries',
    name: 'Martial Arts Injuries',
    keywords: ['martial arts injury', 'fighting injury', 'combat sports', 'training injury'],
    symptoms: ['martial arts pain', 'training injury', 'sparring injury', 'technique pain'],
    relatedConditions: ['acute_injury', 'overuse_injury', 'technique_issues'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['injury_assessment', 'rehabilitation', 'prevention'],
    treatmentApproaches: ['injury assessment', 'rehabilitation', 'prevention strategies'],
    urgencyLevel: 'medium',
    typicalDuration: '4-10 sessions',
    expectedOutcomes: ['injury recovery', 'better technique', 'injury prevention'],
    bodyParts: ['various'],
    severity: 'moderate'
  },
  {
    id: 'swimming_injuries',
    name: 'Swimming Injuries',
    keywords: ['swimming injury', 'swimming pain', 'swimmer\'s shoulder', 'pool injury'],
    symptoms: ['shoulder pain from swimming', 'neck pain', 'overuse injury', 'technique issues'],
    relatedConditions: ['swimmer\'s_shoulder', 'overuse_injury', 'technique_issues'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['technique_analysis', 'injury_treatment', 'prevention'],
    treatmentApproaches: ['technique analysis', 'injury treatment', 'prevention strategies'],
    urgencyLevel: 'low',
    typicalDuration: '4-8 sessions',
    expectedOutcomes: ['pain-free swimming', 'better technique', 'injury prevention'],
    bodyParts: ['shoulders', 'neck', 'back'],
    severity: 'mild'
  },
  {
    id: 'tennis_elbow',
    name: 'Tennis Elbow',
    keywords: ['tennis elbow', 'lateral epicondylitis', 'elbow pain', 'gripping pain'],
    symptoms: ['elbow pain', 'gripping pain', 'forearm pain', 'can\'t grip properly'],
    relatedConditions: ['lateral_epicondylitis', 'overuse_injury', 'grip_issues'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['injury_assessment', 'rehabilitation', 'prevention'],
    treatmentApproaches: ['injury assessment', 'rehabilitation', 'grip strengthening'],
    urgencyLevel: 'medium',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['pain relief', 'better grip', 'injury prevention'],
    bodyParts: ['elbow', 'forearm', 'wrist'],
    severity: 'moderate'
  },
  {
    id: 'golfer\'s_elbow',
    name: 'Golfer\'s Elbow',
    keywords: ['golfer\'s elbow', 'medial epicondylitis', 'golf elbow', 'elbow pain'],
    symptoms: ['inner elbow pain', 'gripping pain', 'forearm pain', 'can\'t grip'],
    relatedConditions: ['medial_epicondylitis', 'overuse_injury', 'grip_issues'],
    recommendedPractitioners: ['sports_therapist', 'osteopath'],
    recommendedServices: ['injury_assessment', 'rehabilitation', 'prevention'],
    treatmentApproaches: ['injury assessment', 'rehabilitation', 'grip strengthening'],
    urgencyLevel: 'medium',
    typicalDuration: '6-12 sessions',
    expectedOutcomes: ['pain relief', 'better grip', 'injury prevention'],
    bodyParts: ['elbow', 'forearm', 'wrist'],
    severity: 'moderate'
  }
];

export interface ConversationStage {
  stage: 'greeting' | 'gathering_symptoms' | 'clarifying_needs' | 'ready_for_recommendations' | 'booking_assistance';
  questions: string[];
  suggestions: string[];
}

export const conversationFlow: Record<string, ConversationStage> = {
  greeting: {
    stage: 'greeting',
    questions: [
      "What brings you here today?",
      "How can I help you find the right practitioner?",
      "What symptoms or concerns are you experiencing?",
      "What's bothering you today?",
      "How can I help you feel better?"
    ],
    suggestions: [
      "I have back pain",
      "I hurt myself playing sports",
      "I need stress relief massage",
      "I'm recovering from surgery",
      "I have neck pain",
      "I need help with posture",
      "I can't sleep properly",
      "I have headaches",
      "My shoulder hurts",
      "I work at a computer all day",
      "I'm pregnant and my back hurts",
      "I have knee problems",
      "I need help with my hip",
      "My foot/ankle is painful",
      "I have jaw problems",
      "I'm getting older and everything aches",
      "I work from home and my back is killing me",
      "I hurt myself at the gym",
      "I have runner's knee",
      "I can't sit at my desk anymore",
      "I'm a parent and my back is destroyed",
      "I have tennis elbow",
      "I hurt myself hiking",
      "I have cycling pain",
      "I'm a student with neck pain",
      "I hurt myself dancing",
      "I have golf elbow",
      "I'm a weekend warrior with injuries",
      "I hurt myself doing yoga",
      "I have swimming shoulder pain",
      "I hurt myself doing martial arts",
      "I'm a new mom with back pain",
      "I have menopause joint pain",
      "I hurt myself gardening",
      "I have driving pain",
      "I wake up with pain every morning"
    ]
  },
  gathering_symptoms: {
    stage: 'gathering_symptoms',
    questions: [
      "Can you tell me more about your symptoms?",
      "When did this start?",
      "What makes it better or worse?",
      "Have you tried any treatments before?",
      "How long have you had this?",
      "Is it getting worse or staying the same?",
      "Does it affect your daily activities?"
    ],
    suggestions: [
      "It started recently",
      "It's been going on for months",
      "It gets worse with activity",
      "Rest helps",
      "I haven't tried anything yet",
      "It's getting worse",
      "It affects my work",
      "I can't do my usual activities",
      "It's constant",
      "It comes and goes",
      "It's worse in the morning",
      "It's worse at night",
      "I've tried physio but it didn't help",
      "Painkillers don't work",
      "I need something different",
      "I've been to doctors but they don't know",
      "I think it's from my job",
      "I hurt myself working out",
      "I can't sit for long periods",
      "I wake up in pain",
      "I can't lift anything",
      "I can't sleep because of the pain",
      "I've tried everything",
      "Nothing seems to help",
      "I'm desperate for relief",
      "I can't afford to be off work",
      "I need to get back to my sport",
      "I'm worried it's something serious",
      "I've had this for years",
      "It's affecting my quality of life"
    ]
  },
  clarifying_needs: {
    stage: 'clarifying_needs',
    questions: [
      "What's your main goal?",
      "How urgent is this?",
      "Do you have any preferences for treatment type?",
      "What's your budget range?",
      "What would success look like for you?",
      "Are you looking for quick relief or long-term solutions?"
    ],
    suggestions: [
      "I want to get back to sports",
      "I need pain relief",
      "I want to prevent future issues",
      "I prefer gentle treatment",
      "I need something quick",
      "I'm not in a rush",
      "I want to understand what's wrong",
      "I need help with my posture",
      "I want to feel relaxed",
      "I need to get back to work",
      "I want to sleep better",
      "I need ongoing maintenance",
      "I prefer natural treatments",
      "I need someone experienced",
      "I want to avoid surgery",
      "I need to get back to the gym",
      "I want to be able to lift my kids",
      "I need help with my desk setup",
      "I want to run without pain",
      "I need someone who understands athletes",
      "I want to prevent this from happening again",
      "I need help with my form",
      "I want to get back to hiking",
      "I need help with my bike fit",
      "I want to dance without pain",
      "I need help with my pregnancy",
      "I want to get back to martial arts",
      "I need help with my swimming technique",
      "I want to garden without pain",
      "I need help with my sleep position",
      "I want to drive without pain",
      "I need help with my menopause symptoms",
      "I want to get back to yoga",
      "I need help with my postpartum recovery"
    ]
  },
  ready_for_recommendations: {
    stage: 'ready_for_recommendations',
    questions: [
      "Based on what you've told me, here are my recommendations:",
      "Would you like to know more about any of these practitioners?",
      "Are you ready to book a session?"
    ],
    suggestions: [
      "Tell me more about this practitioner",
      "Show me other options",
      "I'd like to book now",
      "What should I expect from treatment?"
    ]
  },
  booking_assistance: {
    stage: 'booking_assistance',
    questions: [
      "Great! Let me help you book with this practitioner.",
      "What time works best for you?",
      "Do you have any questions about the session?"
    ],
    suggestions: [
      "Book for this week",
      "Show me available times",
      "What should I bring?",
      "How much will it cost?"
    ]
  }
};
