#!/usr/bin/env node
/**
 * Build script: MJML → HTML → Juice (inline CSS) → _layout-compiled.ts
 * Run before deploy: npm run email:build
 * Output: supabase/functions/send-email/_layout-compiled.ts
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const MJML_PATH = path.join(ROOT, "scripts", "email-templates", "base.mjml");
const OUTPUT_PATH = path.join(
  ROOT,
  "supabase",
  "functions",
  "send-email",
  "_layout-compiled.ts",
);

async function build() {
  const mjml = require("mjml");
  const juice = require("juice");

  const mjmlSource = fs.readFileSync(MJML_PATH, "utf8");
  const { html } = mjml(mjmlSource, { minify: false });
  const inlined = juice(html);

  const escaped = inlined
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const tsContent = `// Auto-generated by scripts/build-emails.js - do not edit
// Run: npm run email:build
export const LAYOUT_TEMPLATE = \`${escaped}\`
`;

  fs.writeFileSync(OUTPUT_PATH, tsContent, "utf8");
  console.log("Email layout built:", OUTPUT_PATH);
}

build().catch((err) => {
  console.error("Email build failed:", err);
  process.exit(1);
});
