// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let VITE_ENV: any = undefined;
try {
  // @ts-expect-error import.meta may not exist in test/runtime
  VITE_ENV = (import.meta as any)?.env;
} catch {
  VITE_ENV = undefined;
}

const SUPABASE_URL = (VITE_ENV?.VITE_SUPABASE_URL || process.env.VITE_SUPABASE_URL)?.trim() || 'https://aikqnvltuwwgifuocvto.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = (VITE_ENV?.VITE_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY)?.trim() || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpa3Fudmx0dXd3Z2lmdW9jdnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTk5NDgsImV4cCI6MjA3MTE5NTk0OH0.PJAKAkbAfp2PP4DXelMpIzhUZZUE5SVoKPzN0JJSRac';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required Supabase environment variables. ' +
    'Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your environment.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Keep session persistence so users can sign in reliably in SPA
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
    detectSessionInUrl: true,
    storageKey: 'theramate-auth',
    onAuthStateChange: (_event, _session) => {
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'theramate-client'
    }
  }
});